### ISSUE TITLE
Git Pages 

### ISSUE THREAD

**Issue by Tiago1604** [fga-eps-mds/2023.1-Biblioteca-Relatorios-Git#15]
**Objetivos:**

Estudar a respeito do Git Pages e desenvolvermos uma página para o projeto

**Atividades já realizadas:**

- [x] Estudo a respeito de Git Pages
- [x] Página do projeto criada

**Comment by JeffersonSenaa** [comment]
A página do projeto foi criada e será atualizada com o desenvolvimento do projeto.
