### ISSUE TITLE
Estudo/Treinamento - Python 

### ISSUE THREAD

**Issue by PedroHhenriq** [fga-eps-mds/2023.1-Biblioteca-Relatorios-Git#7]
# Estudo e Treinamento acerca de Python

## Atividade a ser realizada

Ter um estudo básico sobre o Python e estabelecer um treinamento, se possível um documento ou qualquer coisa do tipo, de forma que o restante do grupo possa aprender de forma mais simples ou consultar os comandos básicos;

- [ ] Os membros designados fizeram um estudo básico acerca da linguagem ou já sabiam dela previamente;
- [x] Foi criado um treinamento ou documento organizando os comandos básicos do Python para os demais membros;

Links e documentos úteis:

- Resumo dos conceitos básicos de Python: https://unbbr-my.sharepoint.com/:w:/g/personal/200049020_aluno_unb_br/EQYVJnOuX2tFsDwPXPMUvhQBUskXFZxK7qGoMw9OIYqiGA?e=koLayL

- Tutorial python: https://docs.python.org/pt-br/3/tutorial/index.html 

Quem estudou ou tem domínio:

- [x] Gabriel
- [x] Jefferson
- [x] Luana
- [x] Mateus
- [x] Pedro
- [x] Rodrigo
- [x] Tiago

**Comment by gabrie1barbosa** [comment]
Tá aberto pra edição, Pedro.
